name: pharmacy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.2.2
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
